name: Generate JavaDoc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate JavaDoc
        run: mvn javadoc:javadoc

      - name: Copy JavaDoc to docs
        run: |
          rm -rf docs
          mkdir docs
          cp -r target/site/apidocs/* docs/

      - name: Commit and Push Docs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs
          git commit -m "Auto update JavaDoc" || echo "No changes"
          git push
