name: Generate JavaDoc

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate JavaDoc
        run: mvn javadoc:javadoc

      - name: Deploy JavaDoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site
