name: Deploy Using Central Workflow

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag"
        required: true
      environment:
        description: "Environment"
        required: false
        default: dev

jobs:
  deploy:
    uses: raghavmemani/demo1/.github/workflows/deploy-reusable.yml@main
    with:
      release_tag: ${{ inputs.release_tag }}
      environment: ${{ inputs.environment }}