name: Resuable Maven Deploy Workflow
permissions:
  contents: write
  actions: write


on:
  workflow_dispatch:
    inputs:
      artifact_id:
        description: "Select the artifact to build and deploy (auto-updated)"
        required: true
        type: choice
        options: [helper, api, service, all]


jobs:
  build:
    uses: raghavmemani/CENTRAL-REPOSITORY/.github/workflows/maven-reusable.yml@main
    with:
      release_tag: ${{ inputs.artifact_id}}
