name: Reusable Maven Deploy Workflow

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      artifact_id:
        description: "Select the artifact to build and deploy"
        required: true
        type: choice
        options: [helper, api, service, all]

jobs:
  build:
    uses: raghavmemani/central_repository12/.github/workflows/maven.yml@main
    with:
      artifact_id: ${{ inputs.artifact_id }}